baseURL = "http://pianomanfrazier.com" #TODO: change to https when available
title = "Ryan Frazier's Blog"
languageCode = "en-us"
author = "Ryan Frazier"
canonifyurls = true
enableEmoji = true
theme = "black-and-light"

#pygmentsstyle = "bw"
#pygmentsstyle = "friendly"
pygmentsstyle = "manni"
pygmentscodefences = true

[params]
	sitename = "Ryan Frazier's Blog"
	description = "Ramblings of Ryan Frazier: Programmer, Musician, and Educator"
	dateform = "January 2, 2006"

[[menu.main]]
	name = "About"
	url  = "/about"
[[menu.main]]
	name = "Projects"
	url  = "https://github.com/pianomanfrazier"
[[menu.main]]
    name = "RSS"
    url  = "/index.xml"

