baseURL = "https://pianomanfrazier.com"
title = "Ryan Frazier's Blog"
languageCode = "en-us"
author = "Ryan Frazier"
canonifyurls = true
enableEmoji = true
theme = "black-and-light"

pygmentsstyle = "manni"
pygmentscodefences = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[params]
	sitename = "Ryan Frazier's Blog"
	description = "Ramblings of Ryan Frazier: Programmer, Musician, and Educator"
	dateform = "January 2, 2006"
  github = "pianomanfrazier"
  linkedin = "pianomanfrazier"
	twitter = "pianomanfrazier"
  rss = true

[[menu.main]]
	name = "About"
	url  = "/about"
[[menu.main]]
    name = "Tags"
    url  = "/tags"

