baseURL = "https://pianomanfrazier.github.io"
title = "Ryan Frazier's Blog"
languageCode = "en-us"
author = "Ryan Frazier"
canonifyurls = true
theme = "black-and-light"

#pygmentsstyle = "bw"
pygmentsstyle = "friendly"
pygmentscodefences = true

[params]
	sitename = "Ryan Frazier's Blog"
	description = "The coding blog of Ryan Frazier. Notes, tips, and tricks."

[[menu.main]]
	name = "About"
	url  = "/about"
[[menu.main]]
	name = "Projects"
	url  = "https://github.com/pianomanfrazier"
#[[menu.main]]
#	name = "Resume"
#	url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"

